/*
 * Golem Market API
 *
 * Market API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace GolemMarketMockAPI.MarketAPI.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ProviderPropertyQuery : ProviderEvent, IEquatable<ProviderPropertyQuery>
    { 
        /// <summary>
        /// Gets or Sets RequestorDesc
        /// </summary>
        [DataMember(Name="requestorDesc")]
        public Object RequestorDesc { get; set; }

        /// <summary>
        /// Gets or Sets QueryId
        /// </summary>
        [DataMember(Name="queryId")]
        public string QueryId { get; set; }

        /// <summary>
        /// Gets or Sets QueriedProps
        /// </summary>
        [DataMember(Name="queriedProps")]
        public List<string> QueriedProps { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProviderPropertyQuery {\n");
            sb.Append("  RequestorDesc: ").Append(RequestorDesc).Append("\n");
            sb.Append("  QueryId: ").Append(QueryId).Append("\n");
            sb.Append("  QueriedProps: ").Append(QueriedProps).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ProviderPropertyQuery)obj);
        }

        /// <summary>
        /// Returns true if ProviderPropertyQuery instances are equal
        /// </summary>
        /// <param name="other">Instance of ProviderPropertyQuery to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProviderPropertyQuery other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    RequestorDesc == other.RequestorDesc ||
                    RequestorDesc != null &&
                    RequestorDesc.Equals(other.RequestorDesc)
                ) && 
                (
                    QueryId == other.QueryId ||
                    QueryId != null &&
                    QueryId.Equals(other.QueryId)
                ) && 
                (
                    QueriedProps == other.QueriedProps ||
                    QueriedProps != null &&
                    QueriedProps.SequenceEqual(other.QueriedProps)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (RequestorDesc != null)
                    hashCode = hashCode * 59 + RequestorDesc.GetHashCode();
                    if (QueryId != null)
                    hashCode = hashCode * 59 + QueryId.GetHashCode();
                    if (QueriedProps != null)
                    hashCode = hashCode * 59 + QueriedProps.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ProviderPropertyQuery left, ProviderPropertyQuery right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ProviderPropertyQuery left, ProviderPropertyQuery right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
